name: Run Tests
on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install every service dependencies
        run: npm run install:all

      - name: Run all services tests
        run: npm run test:all

# TODO: Add a job to build the Docker images with Docker Compose with the resolving the use of .env file
#  build-docker-images-with-docker-compose:
#    runs-on: ubuntu-latest
#    needs: run-tests
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build the Docker image with Docker Compose
#        run: docker-compose build --no-cache --force-rm